/**
 * Mission-region tile bundles. Each region maps to a single .pmtiles file
 * served from /regions/<key>.pmtiles.
 *
 * Add or update a region:
 *   scripts/add_region.py --name <key> --lat <lat> --lon <lon> --radius-km <km>
 *
 * The block between REGIONS-START and REGIONS-END is auto-generated by
 * add_region.py — manual edits inside it will be lost on the next run.
 */
// REGIONS-START
export const REGIONS = {
  umd: {
    label: "UMD / College Park",
    pmtiles: "/regions/umd.pmtiles",
    center: [-76.9378, 38.9897],
    zoom: 13,
  },
};
// REGIONS-END

const STORAGE_KEY = "active-region";

export function getActiveRegionKey() {
  if (typeof window !== "undefined") {
    const stored = window.localStorage?.getItem(STORAGE_KEY);
    if (stored && REGIONS[stored]) return stored;
    if (window.__ACTIVE_REGION__) return window.__ACTIVE_REGION__;
  }
  return process.env.NEXT_PUBLIC_ACTIVE_REGION || "umd";
}

export function setActiveRegionKey(key) {
  if (typeof window === "undefined") return;
  if (!REGIONS[key]) return;
  window.localStorage?.setItem(STORAGE_KEY, key);
}

export function getActiveRegion() {
  const key = getActiveRegionKey();
  return REGIONS[key] || REGIONS.umd;
}
